### ISSUE TITLE
Uncaught DOMException in Chrome Console

### ISSUE THREAD

**Issue by atifwaqar** [kunalnagar/facebook-comments#2]
Hi,
I have downloaded your code from GH, and just by adding the following code : 
```
<link rel="import" href="/sys/facebook-comments/facebook-comments.html">
```
I am getting following exception in Chrome console : 
```
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'undefined'. The type name is invalid.
    at window.Polymer (http://localhost:8080/sys/polymer/polymer-micro.html:62:21)
    at http://localhost:8080/sys/facebook-comments/facebook-comments.html:61:2
```

**Comment by alejost848** [comment]
Are you using the latest Polymer version? If you do, this error might be because the element was built with a pre-Polymer 1.0 version, hence the incompatibility.

**Comment by atifwaqar** [comment]
@alejost848 Yes I am using Polymer 1.0. So this explains everything. 
But do you guys plan to update your code for Latest Polymer?

**Comment by alejost848** [comment]
Well, I'm not a contributor to this repo, but I was considering the idea about creating a facebook-comments element for Polymer 1.0 on my own. The thing is that just by using the Facebook SDK the syntax is just like the one of a web component using the attributes listed [here](https://developers.facebook.com/docs/plugins/comments/#settings):

```html
<div 
  class="fb-comments"
  data-href="https://developers.facebook.com/docs/plugins/comments#configurator"
  data-numposts="5"
  data-colorscheme="light"
  data-order-by="time"
  data-width="500">
</div>
```
So I'm having doubts of how useful it would be to create an element just for wrapping this div because of the performance cost of having to stamp another element in the DOM (I'm not sure if this would be significant at all though).

What are your thoughts @atifwaqar?

**Comment by atifwaqar** [comment]
Well, I do have a little knowledge about facebook SDK, but I'd prefer to use a web-component for all of the facebook features, like Comments, Shares, Likes, login, etc. 
And the reason is that when I use webcomponent in my code, my HTML code stays neat and clean. And that I don't have to learn/read anything from facebook SDK. 
And I'd guess there are other ppl as well who think the same as I do.

**Comment by alejost848** [comment]
You don't need any advanced knowledge of the SDK, all you have to do is use this little snippet in your `index.html` file. It is necessary and should be separate from the rest of your code since it's only needed once. You add this code and you'll get access to all those Facebook features you are mentioning (comments, shares, likes, login, etc).

```html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=[YOUR_APP_ID]";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```

Whether if you are using a web component or just a `<div>` tag, you still need this code. In the end the only difference is going to be the tag that you'll be using to add different features:

```html
<div 
  class="fb-comments"
  data-href="https://developers.facebook.com/docs/plugins/comments#configurator"
  data-numposts="5"
  data-colorscheme="light"
  data-order-by="time"
  data-width="500">
</div>
```
vs.
```html
<facebook-comments
  class="fb-comments"
  data-href="https://developers.facebook.com/docs/plugins/comments#configurator"
  data-numposts="5"
  data-colorscheme="light"
  data-order-by="time"
  data-width="500">
</facebook-comments>
```
My point is that Facebook already simplified their syntax, so creating a web component would just be creating a wrapper to that div. [As it has been discussed before](https://github.com/PolymerElements/paper-menu-button/issues/74#issuecomment-203030650) with the paper-material element:

>"[...] it's a bit of a performance anti-pattern to create a whole custom element just to get a box shadow."

In this case, I don't see any benefit from creating a whole custom element just to wrap something that already behaves like a web component. 

I mean, you could totally do it on your own, this is only my reasoning to why I decided not to create an updated version of this element myself and instead use the default Facebook syntax.

**Comment by kunalnagar** [comment]
@alejost848 @atifwaqar I would gladly accept a PR if either of you is willing to update this to be compatible with the latest Polymer version.
